import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { ContextProvider } from "./context";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Global Dev",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} m-4`}>
        <ContextProvider>
          <h1 className="absolute right-8 top-4 text-5xl">devy</h1>
          <div className="mt-14 text-center text-xl">
            Check out the average developer salaries in any country in the
            world.
          </div>
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
