import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { ContextProvider } from "./context";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Global Dev",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} m-2`}>
        <ContextProvider>
          <div className="flex justify-end">
            <h1 className="absolute mr-5 w-1/5 text-5xl">devy</h1>
          </div>
          <div className="flex justify-center">
            <div className="mt-14 w-7/12 whitespace-normal break-words text-center text-xl font-bold">
              Check out the average developer salaries in any country in the
              world.
            </div>
          </div>
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
